# Site settings
title: "Resumé: Angelica Hjelm Gardner"
description: "Full-Stack Web Developer."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Angelica Hjelm Gardner"
resume_title:                   "Download one page resumé as PDF →"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "angelicahjelmgardner@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • angelicahjelmgardner@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "I am a Web Developer with several years of Front End experience. Now primarily interested in transitioning into Back End positions."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/angelicagardner"
  # resume_linkedin_url:          "https://www.linkedin.com/in/angelica-gardner/"
  # resume_website_url:           "https://angelicagardner.com"
  # resume_medium_url:            "https://medium.com/@angelicagardner"
  resume_pdf_url:                 "https://github.com/angelicagardner/resume/raw/gh-pages/PDF/resume.pdf"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
